### ISSUE TITLE
Raw is Deprecated

### ISSUE THREAD

**Issue by Ctucker9233** [Cron/Symfony-Bundle#123]
I'm on Symfony 6, and I've run into this:

deprecation.INFO: Deprecated: Creation of dynamic property Cron\Job\ShellJob::$raw is deprecated

The notice says the error is here: cron/cron-bundle/Cron/Resolver.php:85. Can someone suggest a fix?

**Comment by weerdenburg** [comment]
I am now using PHP 8.2 and my logs are flooding with:

**ErrorException:**
Deprecated: Creation of dynamic property Cron\Job\ShellJob::$raw is deprecated

Probably using a wrapper is a good way to handle this issue, because Cron\Job\ShellJob is not part of the Symfony-Bundle package. 

But because both packages are maintained by the same user @NoUseFreak, he might be able to make a more elegant fix.
I also don't know if the term 'raw' is the correct name for this property.

Hopefully, @NoUseFreak can help us with this issue or put some extra info in here so we can make the needed pull requests maybe even in both packages.

_For now, I just copied the vendor file to src/Job/ShellJob.php added a public $raw property to it, and added a ref. to this issue._
