### ISSUE TITLE
How can i set the name of command on cron:create

### ISSUE THREAD

**Issue by allanbarbosa** [Cron/Symfony-Bundle#91]
Hello, good morning.

I know this is a dummy question, but let's go.
In the documentation you say that to create a new cron we can execute the commando cron:create.
When i execute this commando this message shows:

```shell
he unique name how the job will be referenced.
Name: [error] Error thrown while running command "cron:create". Message: "Please set a name."


In CronCreateCommand.php line 102:
                      
  Please set a name.  
                      

cron:create [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

How can i set the name of the cron?

**Comment by NoUseFreak** [comment]
Hi @allanbarbosa, Although it should have been possible to create a command using the interactive interface by running the cron:create without arguments. The new change allows you to create using inline arguments.

Hope it helps.

**Comment by renan-arrieiro** [comment]
I`m execute this command with success:
`php bin/console app:3gr:updatePriceStock 19 100`
but when register this in cron_job 
![image](https://user-images.githubusercontent.com/54153114/114387834-4ff10900-9b69-11eb-997c-8d374e01ea05.png)
it apparently does not execute, because there is no return and the execution time is very short.
![image](https://user-images.githubusercontent.com/54153114/114387945-731bb880-9b69-11eb-809a-39a25ab6946a.png)
other commands without arguments work perfectly.
